name: bidirectional_scroll_view
description: Plugin that provides a bidirectional scrollview.
version: 0.1.1
author: Toufik Zitouni <toufiksapps@gmail.com>
homepage: https://github.com/toufikzitouni/flutter-bidirectional_scrollview_plugin

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
